{
 "title": "MyAir",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "patient", "label": "Patient", "query": { "query": "query_result(myair_patient)" } },
   { "name": "device", "label": "Device", "query": { "query": "query_result(myair_device)" } },
   {
    "name": "mask",
    "label": "Mask",
    "query": {
     "query": "query_result(myair_mask{patient=~\"$patient\"})"
    }
   },
   {
    "name": "date",
    "label": "Date",
    "query": {
     "query": "query_result(myair_score{patient=~\"$patient\", mask=~\"$mask\", device=~\"$device\"} != 0)"
    }
   },
   {
    "name": "lastReportDateOld",
    "query": {
     "query": "label_values(myair_total_days_count{patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"},lastReportDate)"
    }
   },
   {
    "name": "lastReportDate",
    "query": {
     "query": "query_result(topk(1, myair_total_days_count{patient=~\"$patient\"}))"
    }
   },
   {
    "name": "daysBack",
    "label": "Show Days",
    "query": "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14"
   }
  ]
 },
 "panels": [
  { "title": "TODAY ($lastReportDate)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MYAIR SCORE",
   "type": "gauge",
   "description": "myAir calculates your score by analyzing your nightly therapy data. The higher your score, the better. You get points based on the following four key categories.\n\nUsage hours, Mask seal, Events per hour, Mask on/off",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(myair_score{patient=~\"$patient\", date=~\"$lastReportDate\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "AVERAGE"
    }
   ]
  },
  {
   "title": "USAGE TIME",
   "type": "stat",
   "description": "The time that the CPAP Device was used.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myair_usage_seconds{date=\"$lastReportDate\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "AHI (SLEEP EVENTS)",
   "type": "stat",
   "description": "Apnea-Hypopnea Index: It's a measure used to determine the severity of sleep apnea by quantifying how often a person's breathing is disrupted during sleep. Specifically, it counts the number of apneas (complete pauses in breathing) and hypopneas (partial reductions in breathing) per hour. ",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "per hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myair_ahi{date=~\"$lastReportDate\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "MASK SEAL",
   "type": "stat",
   "description": "The better your mask seal, the more points you get. This category can help you know if you need to adjust or change your mask to get a better fit. If your mask seal is poor, it can affect your comfort and the quality of your treatment. Your score reduces as your mask leak increases. You can get up to 20 points for minimal mask leak, 10 to 15 points for moderate leak, and 0 to 10 points for higher leak.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myair_mask_seal{date=\"$lastReportDate\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "MASK ON/OFF",
   "type": "stat",
   "description": "The fewer times you take your mask on and off throughout the night, the more points you get. Everyone has to take their mask on and off one time during treatment. So, for example, if you remove your mask one or two times, you get 5 points. However, if you take your mask on and off several times, it can indicate a problem with mask fit or with your sleep in general.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myair_mask_onoff_count{date=\"$lastReportDate\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "USAGE TIME SCORE",
   "type": "bargauge",
   "description": "The point system for usage is calculated in hours and minutes. If you use your therapy for 1 hour you get 10 points, or for 2.3 hours (2 hours, 18 minutes) you get 23 points. The more time you use your therapy, the more points you receive, up to a maximum of 70 points. ",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myair_usage_score{date=\"$lastReportDate\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "AHI SCORE",
   "type": "bargauge",
   "description": "AHI Score. Maximum of 5",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myair_ahi_score{date=\"$lastReportDate\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "MASK SEAL SCORE",
   "type": "bargauge",
   "description": "Mask Seal Score. Maximum of 20\n\nThe better your mask seal, the more points you get. This category can help you know if you need to adjust or change your mask to get a better fit. If your mask seal is poor, it can affect your comfort and the quality of your treatment. Your score reduces as your mask leak increases. You can get up to 20 points for minimal mask leak, 10 to 15 points for moderate leak, and 0 to 10 points for higher leak.",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myair_mask_seal_score{date=~\"$lastReportDate\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "MASK ON/OFF SCORE",
   "type": "bargauge",
   "description": "Mask Seal Score. Maximum of 5\n\nThe fewer times you take your mask on and off throughout the night, the more points you get. Everyone has to take their mask on and off one time during treatment. So, for example, if you remove your mask one or two times, you get 5 points. However, if you take your mask on and off several times, it can indicate a problem with mask fit or with your sleep in general.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myair_mask_onoff_score{date=\"$lastReportDate\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0",
     "legendFormat": "{{date}}"
    }
   ]
  },
  { "title": "HISTORY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "MYAIR SCORE",
   "type": "gauge",
   "description": "myAir calculates your score by analyzing your nightly therapy data. The higher your score, the better. You get points based on the following four key categories.\n\nUsage hours, Mask seal, Events per hour, Mask on/off",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(myair_score{patient=~\"$patient\", date=~\"$date\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "AVERAGE"
    },
    {
     "expr": "max(myair_score{patient=~\"$patient\", date=~\"$date\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "BEST"
    },
    {
     "expr": "min(myair_score{patient=~\"$patient\", date=~\"$date\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "WORST"
    }
   ]
  },
  {
   "title": "AVERAGE USAGE HOURS",
   "type": "stat",
   "description": "The time that the CPAP Device was used. If more than one date is selected, this is an average.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(myair_usage_seconds{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "AVERAGE AHI (SLEEP EVENTS)",
   "type": "stat",
   "description": "Apnea-Hypopnea Index: It's a measure used to determine the severity of sleep apnea by quantifying how often a person's breathing is disrupted during sleep. Specifically, it counts the number of apneas (complete pauses in breathing) and hypopneas (partial reductions in breathing) per hour. ",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "per hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(myair_ahi{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "AVERAGE MASK SEAL",
   "type": "stat",
   "description": "The better your mask seal, the more points you get. This category can help you know if you need to adjust or change your mask to get a better fit. If your mask seal is poor, it can affect your comfort and the quality of your treatment. Your score reduces as your mask leak increases. You can get up to 20 points for minimal mask leak, 10 to 15 points for moderate leak, and 0 to 10 points for higher leak.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(myair_mask_seal{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "AVERAGE MASK ON/OFF",
   "type": "stat",
   "description": "The fewer times you take your mask on and off throughout the night, the more points you get. Everyone has to take their mask on and off one time during treatment. So, for example, if you remove your mask one or two times, you get 5 points. However, if you take your mask on and off several times, it can indicate a problem with mask fit or with your sleep in general.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(myair_mask_onoff_count{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "AVERAGE USAGE HOURS SCORE",
   "type": "bargauge",
   "description": "The point system for usage is calculated in hours and minutes. If you use your therapy for 1 hour you get 10 points, or for 2.3 hours (2 hours, 18 minutes) you get 23 points. The more time you use your therapy, the more points you receive, up to a maximum of 70 points. If more than one date is selected, this is an average.",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(myair_usage_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "AVERAGE AHI SCORE",
   "type": "bargauge",
   "description": "AHI Score. Maximum of 5",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(myair_ahi_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "AVERAGE MASK SEAL SCORE",
   "type": "bargauge",
   "description": "Mask Seal Score. Maximum of 20\n\nThe better your mask seal, the more points you get. This category can help you know if you need to adjust or change your mask to get a better fit. If your mask seal is poor, it can affect your comfort and the quality of your treatment. Your score reduces as your mask leak increases. You can get up to 20 points for minimal mask leak, 10 to 15 points for moderate leak, and 0 to 10 points for higher leak.",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(myair_mask_seal_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "AVERAGE MASK ON/OFF SCORE",
   "type": "bargauge",
   "description": "Mask Seal Score. Maximum of 5\n\nThe fewer times you take your mask on and off throughout the night, the more points you get. Everyone has to take their mask on and off one time during treatment. So, for example, if you remove your mask one or two times, you get 5 points. However, if you take your mask on and off several times, it can indicate a problem with mask fit or with your sleep in general.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(myair_mask_onoff_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "TOTAL USAGE HOURS",
   "type": "stat",
   "description": "The time that the CPAP Device was used. If more than one date is selected, this is an average.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myair_total_usage_seconds{patient=~\"$patient\"}",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "BEST USAGE HOURS",
   "type": "stat",
   "description": "The time that the CPAP Device was used. If more than one date is selected, this is an average.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(myair_usage_seconds{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "BEST AHI (SLEEP EVENTS)",
   "type": "stat",
   "description": "Apnea-Hypopnea Index: It's a measure used to determine the severity of sleep apnea by quantifying how often a person's breathing is disrupted during sleep. Specifically, it counts the number of apneas (complete pauses in breathing) and hypopneas (partial reductions in breathing) per hour. ",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "per hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(myair_ahi{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "BEST  MASK SEAL",
   "type": "stat",
   "description": "The better your mask seal, the more points you get. This category can help you know if you need to adjust or change your mask to get a better fit. If your mask seal is poor, it can affect your comfort and the quality of your treatment. Your score reduces as your mask leak increases. You can get up to 20 points for minimal mask leak, 10 to 15 points for moderate leak, and 0 to 10 points for higher leak.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(myair_mask_seal{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "BEST MASK ON/OFF",
   "type": "stat",
   "description": "The fewer times you take your mask on and off throughout the night, the more points you get. Everyone has to take their mask on and off one time during treatment. So, for example, if you remove your mask one or two times, you get 5 points. However, if you take your mask on and off several times, it can indicate a problem with mask fit or with your sleep in general.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(myair_mask_onoff_count{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "BEST USAGE HOURS SCORE",
   "type": "bargauge",
   "description": "The point system for usage is calculated in hours and minutes. If you use your therapy for 1 hour you get 10 points, or for 2.3 hours (2 hours, 18 minutes) you get 23 points. The more time you use your therapy, the more points you receive, up to a maximum of 70 points. If more than one date is selected, this is an average.",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(myair_usage_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "BEST AHI SCORE",
   "type": "bargauge",
   "description": "AHI Score. Maximum of 5",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(myair_ahi_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "BEST MASK SEAL SCORE",
   "type": "bargauge",
   "description": "Mask Seal Score. Maximum of 20\n\nThe better your mask seal, the more points you get. This category can help you know if you need to adjust or change your mask to get a better fit. If your mask seal is poor, it can affect your comfort and the quality of your treatment. Your score reduces as your mask leak increases. You can get up to 20 points for minimal mask leak, 10 to 15 points for moderate leak, and 0 to 10 points for higher leak.",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(myair_mask_seal_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "BEST  MASK ON/OFF SCORE",
   "type": "bargauge",
   "description": "Mask Seal Score. Maximum of 5\n\nThe fewer times you take your mask on and off throughout the night, the more points you get. Everyone has to take their mask on and off one time during treatment. So, for example, if you remove your mask one or two times, you get 5 points. However, if you take your mask on and off several times, it can indicate a problem with mask fit or with your sleep in general.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(myair_mask_onoff_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "TOTAL USAGE DAYS",
   "type": "stat",
   "description": "The number of days that information is being tracked on dashboard.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myair_total_days_count{patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\",lastReportDate=~\"$lastReportDate\"}",
     "legendFormat": "TOTAL USAGE DAYS"
    }
   ]
  },
  {
   "title": "WORST USAGE HOURS",
   "type": "stat",
   "description": "The time that the CPAP Device was used. If more than one date is selected, this is an average.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(myair_usage_seconds{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "WORST AHI (SLEEP EVENTS)",
   "type": "stat",
   "description": "Apnea-Hypopnea Index: It's a measure used to determine the severity of sleep apnea by quantifying how often a person's breathing is disrupted during sleep. Specifically, it counts the number of apneas (complete pauses in breathing) and hypopneas (partial reductions in breathing) per hour. ",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "per hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(myair_ahi{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "WORST MASK SEAL",
   "type": "stat",
   "description": "The better your mask seal, the more points you get. This category can help you know if you need to adjust or change your mask to get a better fit. If your mask seal is poor, it can affect your comfort and the quality of your treatment. Your score reduces as your mask leak increases. You can get up to 20 points for minimal mask leak, 10 to 15 points for moderate leak, and 0 to 10 points for higher leak.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(myair_mask_seal{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "WORST  MASK ON/OFF",
   "type": "stat",
   "description": "The fewer times you take your mask on and off throughout the night, the more points you get. Everyone has to take their mask on and off one time during treatment. So, for example, if you remove your mask one or two times, you get 5 points. However, if you take your mask on and off several times, it can indicate a problem with mask fit or with your sleep in general.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(myair_mask_onoff_count{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "WORST USAGE HOURS SCORE",
   "type": "bargauge",
   "description": "The point system for usage is calculated in hours and minutes. If you use your therapy for 1 hour you get 10 points, or for 2.3 hours (2 hours, 18 minutes) you get 23 points. The more time you use your therapy, the more points you receive, up to a maximum of 70 points. If more than one date is selected, this is an average.",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(myair_usage_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "WORST AHI SCORE",
   "type": "bargauge",
   "description": "AHI Score. Maximum of 5",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(myair_ahi_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "WORST MASK SEAL SCORE",
   "type": "bargauge",
   "description": "Mask Seal Score. Maximum of 20\n\nThe better your mask seal, the more points you get. This category can help you know if you need to adjust or change your mask to get a better fit. If your mask seal is poor, it can affect your comfort and the quality of your treatment. Your score reduces as your mask leak increases. You can get up to 20 points for minimal mask leak, 10 to 15 points for moderate leak, and 0 to 10 points for higher leak.",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(myair_mask_seal_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "WORST MASK ON/OFF SCORE",
   "type": "bargauge",
   "description": "Mask Seal Score. Maximum of 5\n\nThe fewer times you take your mask on and off throughout the night, the more points you get. Everyone has to take their mask on and off one time during treatment. So, for example, if you remove your mask one or two times, you get 5 points. However, if you take your mask on and off several times, it can indicate a problem with mask fit or with your sleep in general.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(myair_mask_onoff_score{date=~\"$date\", patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"} != 0)",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "MYAIR SCORE ($daysBack days)",
   "type": "bargauge",
   "description": "myAir calculates your score by analyzing your nightly therapy data. The higher your score, the better. You get points based on the following four key categories.\n\nUsage hours, Mask seal, Events per hour, Mask on/off",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk($daysBack, sum(myair_score{patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"}) by (date))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USAGE TIME ($daysBack days)",
   "type": "bargauge",
   "description": "The better your mask seal, the more points you get. This category can help you know if you need to adjust or change your mask to get a better fit. If your mask seal is poor, it can affect your comfort and the quality of your treatment. Your score reduces as your mask leak increases. You can get up to 20 points for minimal mask leak, 10 to 15 points for moderate leak, and 0 to 10 points for higher leak.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk($daysBack, sum(myair_usage_seconds{patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"}) by (date))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AHI ($daysBack days)",
   "type": "bargauge",
   "description": "The better your mask seal, the more points you get. This category can help you know if you need to adjust or change your mask to get a better fit. If your mask seal is poor, it can affect your comfort and the quality of your treatment. Your score reduces as your mask leak increases. You can get up to 20 points for minimal mask leak, 10 to 15 points for moderate leak, and 0 to 10 points for higher leak.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "per hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk($daysBack, sum(myair_ahi{patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"}) by (date))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MASK SEAL ($daysBack days)",
   "type": "bargauge",
   "description": "The better your mask seal, the more points you get. This category can help you know if you need to adjust or change your mask to get a better fit. If your mask seal is poor, it can affect your comfort and the quality of your treatment. Your score reduces as your mask leak increases. You can get up to 20 points for minimal mask leak, 10 to 15 points for moderate leak, and 0 to 10 points for higher leak.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk($daysBack, sum(myair_mask_seal{patient=~\"$patient\", device=~\"$device\", mask=~\"$mask\"}) by (date))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}